server:
  port: 0

spring:
  application:
    name: EUREKA-CLIENT-SAMPLE
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://localhost:8761/eureka"

management:
  server:
    port: 11001
    address: "localhost"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    beans:
      enabled: true
    info:
      enabled: true