server:
  port: 8761

spring:
  application:
    name: discoverService

eureka:
  server:
    enable-self-preservation: true # turn on save mode

  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"